/* Generated By:JavaCC: Do not edit this line. CMSParserConstants.java */
package org.cdlib.xtf.cms;

public interface CMSParserConstants {

  int EOF = 0;
  int NOISE = 1;
  int AND = 2;
  int OR = 3;
  int NOT = 4;
  int BASIC = 5;
  int APOSTROPHE = 6;
  int ACRONYM = 7;
  int COMPANY = 8;
  int EMAIL = 9;
  int HOST = 10;
  int NUM = 11;
  int SYMBOL = 12;
  int ALPHANUM = 13;
  int P = 14;
  int HAS_DIGIT = 15;
  int ALPHA = 16;
  int LETTER = 17;
  int CJK = 18;
  int DIGIT = 19;
  int XTF_SPECIAL = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<NOISE>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<BASIC>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<SYMBOL>",
    "<ALPHANUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
    "<XTF_SPECIAL>",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"\\\'\"",
  };

}
